### ISSUE TITLE
Sometimes, Gajim crashes when loading the .fpr file

### ISSUE THREAD

**Issue by micahflee** [micahflee/pidgin2gajim#1]
After copying fingerprint files into Gajim and then running it, it crashes the first time. After the crash, it looks like it has re-written the .fpr file to be smaller, and re-ordered the contacts in it. When I run Gajim again, it runs fine with most of the saved fingerprints loaded.

```
[micah@spock] ~$ gajim
/home/micah/.local/share/gajim/plugins/gotr/ui.py:40: GtkWarning: Unknown property: GtkMenu.ubuntu-local
  self.B.add_from_file(self.GTK_BUILDER_FILE_PATH)
Traceback (most recent call last):
  File "gajim.py", line 448, in <module>
    interface.run()
  File "/usr/share/gajim/src/gui_interface.py", line 2537, in run
    gajim.plugin_manager = plugins.PluginManager()
  File "/usr/share/gajim/src/plugins/helpers.py", line 129, in __call__
    cls.instance=super(Singleton, cls).__call__(*args,**kw)
  File "/usr/share/gajim/src/plugins/pluginmanager.py", line 105, in __init__
    self.add_plugins(pc)
  File "/usr/share/gajim/src/plugins/helpers.py", line 114, in wrapper
    result = f(*args, **kwargs)
  File "/usr/share/gajim/src/plugins/pluginmanager.py", line 144, in add_plugins
    self.add_plugin(plugin_class)
  File "/usr/share/gajim/src/plugins/helpers.py", line 114, in wrapper
    result = f(*args, **kwargs)
  File "/usr/share/gajim/src/plugins/pluginmanager.py", line 128, in add_plugin
    plugin = plugin_class()
  File "/usr/share/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/usr/share/gajim/src/plugins/plugin.py", line 161, in __init__
    self.init()
  File "/home/micah/.local/share/gajim/plugins/gotr/otrmodule.py", line 289, in init
    self.us[acc].loadTrusts()
  File "/home/micah/.local/share/gajim/plugins/gotr/otrmodule.py", line 227, in loadTrusts
    ctx, acc, proto, fpr, trust = line[:-1].split('\t')
ValueError: need more than 4 values to unpack
```

**Comment by ThomasWaldmann** [comment]
https://github.com/micahflee/pidgin2gajim/blob/master/pidgin2gajim.py#L110

somehow looks like this might be already fixed?

**Comment by xshadow** [comment]
@ThomasWaldmann  Nope, it's still an issue

**Comment by xshadow** [comment]
As a workaround you you could edit the fpr and only copy the verified fingerprints 

> grep verified  output/micah@jabber.ccc.de.fpr >  ~/.local/share/gajim/jabber.ccc.de.fpr
