### ISSUE TITLE
Is this tool still working with current versions of libraries?

### ISSUE THREAD

**Issue by SebAlbert** [micahflee/pidgin2gajim#6]
I first tried running the script as-is, having python3 (which is the "default" python version on my system) complain about missing parentheses in "print" statements. After adding those, I failed on a UnicodeDecodeError, because 'utf-8' couldn't decode the "start byte" (the keys probably just aren't utf-8, but rather binary blobs, but for some reason python3 tries to read them as utf-8).

So I fed the script into python2 (which I guess is what it's supposed to run with) just to bump into a different error:

> Traceback (most recent call last):
>   File "pidgin2gajim.py", line 111, in <module>
>     keys = parse(pidgin_key_filename)
>   File "pidgin2gajim.py", line 96, in parse
>     key['dsakey'] = DSAKey(keytuple, private=True)
>   File "/usr/lib/python2.7/site-packages/potr/compatcrypto/pycrypto.py", line 90, in **init**
>     self.priv = DSA.construct(key)
>   File "/usr/lib/python2.7/site-packages/Crypto/PublicKey/DSA.py", line 370, in construct
>     key = self._math.dsa_construct(*tup)
> TypeError: argument 5 must be long, not str

Maybe the libraries used have changed their ways of doing stuff? So, is the code still working for anybody with current libraries?
(I'm on ArchLinux, just in case that makes any difference)

**Comment by SebAlbert** [comment]
I got it working by removing the binary-crappy fingerprint of one of my accounts from the purple (pidgin) otr keyfile before running pidgin2gajim, and, for python3, changing the write mode for the .key3 file (but not for the .fpr file) from "w" to "wb". Thanks for this tool.
